from Gieldy.Binance.API_initiation_Binance_AB_USDT import API_initiation as API_Binance_AB_USDT
from Gieldy.Kucoin.API_initiation_Kucoin_AB_USDT import API_initiation as API_Kucoin_AB_USDT
from Gieldy.Gateio.API_initiation_Gateio_AB_USDT import API_initiation as API_Gateio_AB_USDT
from Gieldy.Okex.API_initiation_Okex_AB_USDT import API_initiation as API_Okex_AB_USDT

print(API_Okex_AB_USDT())